name: Container Image Build CI

on:
  push:
    branches:
      - main
      - deploy-*
    tags: 
      - v*.*.*

env:
  IMAGE_NAME: ghcr.io/savvythelegend/robotoff

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.6.0
        buildkitd-flags: --debug

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=pr
          type=ref,event=branch
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        target: runtime
        push: true
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
